### ISSUE TITLE
Gestire errori di difformità dei dati durante login e registrazione

### ISSUE THREAD

**Issue by aka-buccia** [aka-buccia/JFXPRJCT#10]
Sostituire gli alert message con una finestra più gradevole

**Comment by aka-buccia** [comment]
Al posto di finestre di alert ho optato per contornare di rosso le caselle vuote e scrivere un messaggio di errore sopra i bottoni. Graficamente va sistemata al momento del cambio di palette

**Comment by AnouarElKihal** [comment]
Aggiungere il contorno di rosso delle caselle vuote o errate nella scena di login
